---
- hosts: all
  become: true
  pre_tasks:
    - name: update repo cache
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Debian"

- hosts: all
  become: true
  roles:
    - base

- hosts: pi_web_servers
  become: true
  roles:
    - pi_web_servers

- hosts: pi_db_servers
  become: true
  roles:
    - pi_db_servers

- hosts: workstations
  become: true
  roles:
    - workstations
