---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"

- hosts: pi_servers
  become: true
  tasks:
    - name: install apache and php packages for Debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

- hosts: pi_db_servers
  become: true
  tasks:
    - name: install mariadb package
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"
