---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"

- hosts: pi_web_servers
  become: true
  tasks:
    - name: install apache and php packages for Debian
      tags: pi_web_servers,apache,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: copy default html file for site
      tags: pi_web_servers,apache,debian
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: pi_db_servers
  become: true
  tasks:
    - name: install mariadb package
      tags: pi_db_servers,mariadb,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"
